services:
  mock-service:
    build:
      context: .
      dockerfile: apps/mock-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    networks:
      - nestjs-benchmark

  nestjs-fastify-axios:
    build:
      context: .
      dockerfile: apps/nestjs-fastify-axios/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MOCK_SERVICE_URL=http://mock-service:3001/api/data
    depends_on:
      - mock-service
    networks:
      - nestjs-benchmark

  nestjs-fastify-undici:
    build:
      context: .
      dockerfile: apps/nestjs-fastify-undici/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MOCK_SERVICE_URL=http://mock-service:3001/api/data
    depends_on:
      - mock-service
    networks:
      - nestjs-benchmark

  nestjs-express-axios:
    build:
      context: .
      dockerfile: apps/nestjs-express-axios/Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MOCK_SERVICE_URL=http://mock-service:3001/api/data
    depends_on:
      - mock-service
    networks:
      - nestjs-benchmark

networks:
  nestjs-benchmark:
    driver: bridge