services:
  mock-service-node24:
    build:
      context: .
      dockerfile: apps/mock-service/Dockerfile
      args:
        NODE_VERSION: 24
    ports:
      - "3021:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    networks:
      - nestjs-benchmark-node24

  nestjs-fastify-axios-node24:
    build:
      context: .
      dockerfile: apps/nestjs-fastify-axios/Dockerfile
      args:
        NODE_VERSION: 24
    ports:
      - "3022:3002"
    environment:
      - PORT=3002
      - MOCK_SERVICE_URL=http://mock-service-node24:3001/api/data
    depends_on:
      - mock-service-node24
    networks:
      - nestjs-benchmark-node24

  nestjs-fastify-undici-node24:
    build:
      context: .
      dockerfile: apps/nestjs-fastify-undici/Dockerfile
      args:
        NODE_VERSION: 24
    ports:
      - "3023:3003"
    environment:
      - PORT=3003
      - MOCK_SERVICE_URL=http://mock-service-node24:3001/api/data
    depends_on:
      - mock-service-node24
    networks:
      - nestjs-benchmark-node24

  nestjs-express-axios-node24:
    build:
      context: .
      dockerfile: apps/nestjs-express-axios/Dockerfile
      args:
        NODE_VERSION: 24
    ports:
      - "3024:3004"
    environment:
      - PORT=3004
      - MOCK_SERVICE_URL=http://mock-service-node24:3001/api/data
    depends_on:
      - mock-service-node24
    networks:
      - nestjs-benchmark-node24

networks:
  nestjs-benchmark-node24:
    driver: bridge